# Generated by Django 4.2.4 on 2023-08-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predimage",
            name="image",
            field=models.ImageField(
                upload_to="C:/Users/moyin/OneDrive/Desktop/DEEP LEARNING/prediction_app/predictionsite/pictures/uploads"
            ),
        ),
    ]
