# Generated by Django 4.2.4 on 2023-08-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictapp", "0002_alter_predimage_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="C:/Users/moyin/OneDrive/Desktop/DEEP LEARNING/prediction_app/predictionsite/pictures/uploads"
                    ),
                ),
                ("predicted_class", models.CharField(max_length=100)),
            ],
        ),
    ]
